### ISSUE TITLE
Get automatic updates for kopium/kube and upstream crd releases

### ISSUE THREAD

**Issue by clux** [kube-rs/gateway-api-rs#1]
Was trying to think of a way to automatically deal with upstream updates, and you've got a couple of things you need to care about here:

- kopium updates -> smarter schemas, should release updates if output changed
- kube updates -> should regenerate schemas to avoid incompatible version problems for users (this library pins kube and k8s-openapi)
- upstream crd updates -> should regenerate, actual api changes

You could maybe do a nightly cron job that checks for any of these updating, and effectively reconciling out a new version as a result of this:

```sh
if ! [[ $(cargo outdated -wd1 -p kube) =~ "up to date" ]]; then
  cargo upgrade kube
fi
if ! [[ $(cargo outdated -wd1 -p k8s-openapi) =~ "up to date" ]]; then
  cargo upgrade k8s-openapi
fi
# something to check kopium version
# something to detect crd updates from gateway-api

# if anything changed
if something_changed;
  cargo release minor --execute
fi
```

those rely on `cargo-edit`, `cargo-outdated` and `cargo-release` (which there may be some github actions for).

Alternatively, you could just rely on dependabot to detect kopium/kube/k8s-openapi version changes, and manually release this.

**Comment by shaneutt** [comment]
After thinking this over I've decided to go with the dependabot route for the moment, now implemented in:

https://github.com/kube-rs/gateway-api-rs/commit/76aa798933fe5acaa873410d62749a775ecaa780

This would seem to be sufficient for now, and we'll see about more complete automation of the process if it starts to be a burden.
