### ISSUE TITLE
Types should include Status Reason/Condition

### ISSUE THREAD

**Issue by EItanya** [kube-rs/gateway-api-rs#19]
Currently the Status Reason/Conditions are missing from the generated types. See [`RouteConditionReason`](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.RouteConditionReason) and [`RouteConditionType`](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.RouteConditionReason). These are not directly referenced by the openapi schema because they are implicitly considered the String values you _should_ use. 

This is by no means a "requirement" as copying those types over is acceptable for now, but it would definitely be easier to implement this API if those types could also be generated somehow.

**Comment by shaneutt** [comment]
Yes indeed, that sounds good.

Do you have a project actively using this library?

**Comment by EItanya** [comment]
I do, but not quite ready for public consumption. Hoping to Open Source it in the next couple weeks!
