### ISSUE TITLE
Update to V1 Core APIs

### ISSUE THREAD

**Issue by EItanya** [kube-rs/gateway-api-rs#20]
The v1.0.0-rc1 version of the Core Gateway APIs were recently released, they should be in a stable enough format to pick up, or at least begin the work to make sure there aren't any gotchas.

**Comment by shaneutt** [comment]
If you're interested in doing this, there's a script for it:

https://github.com/kube-rs/gateway-api-rs/blob/main/update.sh

In theory it should be:

1. update the `VERSION`
2. run the script
3. success!

Though in practice there will probably be a couple more small things.

Let us know if you wanna do it, the help is definitely appreciated!

**Comment by EItanya** [comment]
The one thing that worried me is that I remember the spec saying they were updating to CEL validation, and the current conversion tool uses `OpenAPI`, so 🤞. I'll give it a go hopefully tomorrow or the next day.

**Comment by EItanya** [comment]
#21

**Comment by shaneutt** [comment]
Tagged `v0.6.0` on top of your changes from #21

**Comment by shaneutt** [comment]
`v0.8.2` includes the full `v1.0.0` release now, so this should be all set!
