### ISSUE TITLE
Enable doctests in CI

### ISSUE THREAD

**Issue by shaneutt** [kube-rs/gateway-api-rs#49]
Currently we're not running [doctests](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html) in CI due to a problem with our generated API code from `kopium`, wherein the docs generated trigger and then fail testing attempts. The purpose of this task is to straighten that out and make sure we have unit and doctests running for PRs.

**Comment by shaneutt** [comment]
I've created https://github.com/kube-rs/kopium/issues/264 in order to fix this in `kopium` itself.

**Comment by clux** [comment]
Should be possible now in https://github.com/kube-rs/kopium/releases/tag/0.21.1

**Comment by shaneutt** [comment]
Thanks @clux and @alexsnaps!

**Comment by shaneutt** [comment]
Resolved by d08fb12cb7442aff96914589fd49754c6d42d2c2 and bdf0fda26761d090084ffc76d6189f0bff18ea15
