### ISSUE TITLE
Upgrade to Gateway API v1.2.0 release

### ISSUE THREAD

**Issue by blinsay** [kube-rs/gateway-api-rs#60]
I just noticed that the Gateway APIs v1.2.0 is out. It'd great to have support for it here.

https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.2.0

EDIT: (Sorry about the issue title spam 😞)

**Comment by blinsay** [comment]
Awesome! Is there anything else we have to do to get the release out to crates.io?

**Comment by shaneutt** [comment]
Had to do some `kube-rs` and `hyper` dependency updates first, but now we're all set: https://crates.io/crates/gateway-api/0.11.0

Please create an issue if you run into any troubles!
